{{- if .Values.deployment.istioEnabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  hosts:
  - "{{ .Release.Name }}.spicynoodle.xyz"
  gateways:
  - cinema-gateway
  http:
  - match:
    - uri:
        prefix: /movies
    route:
    - destination:  
        host: "{{ .Values.servicesName.movies }}.{{ .Release.Name }}.{{ .Values.istioVirtualService.localServicesEndpoint }}"
        port:
          number: 80
  - match:
    - uri:
        prefix: /bookings
    route:
    - destination:
        host: "{{ .Values.servicesName.bookings }}.{{ .Release.Name }}.{{ .Values.istioVirtualService.localServicesEndpoint }}"
        port:
          number: 80
  - match:
    - uri:
        prefix: /users
    route:
    - destination:
        host: "{{ .Values.servicesName.users }}.{{ .Release.Name }}.{{ .Values.istioVirtualService.localServicesEndpoint }}"
        port:
          number: 80
  - match:
    - uri:
        prefix: /showtimes
    route:
    - destination:
        host: "{{ .Values.servicesName.showtimes }}.{{ .Release.Name }}.{{ .Values.istioVirtualService.localServicesEndpoint }}"
        port:
          number: 80
{{- end }}